title: Bastard Keyboards Documentation
description: Official Bastard Keyboards documentation

logo: "/assets/img/bk-1.png"
favicon_ico: "/assets/img/favicon.ico"

markdown: kramdown

remote_theme: just-the-docs/just-the-docs

exclude:
  - .jekyll-cache
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - _site/
  - building-locally.md

plugins:
  - jekyll-default-layout
  - jekyll-remote-theme

# Aux links for the upper right navigation
aux_links:
  "Bastard Keyboards on GitHub":
    - "https://github.com/bastardkb"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# External navigation links
nav_external_links:
  - title: Bastard Keyboards on GitHub
    url: https://github.com/bastardkb
  - title: Bastard Keyboards website
    url: https://bastardkb.com
  - title: Bastard Keyboards discord
    url: https://bastardkb.com/discord

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Nice boxes for visibility
callouts:
  tip:
    title: Tip
    color: blue
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: grey-lt
  question:
    title: Question
    color: yellow

color_scheme: bkb
